services:
  database:
    container_name: database_ereader
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: ereader
      MYSQL_USER: ereader
      MYSQL_PASSWORD: ereader
    ports:
      - '127.0.0.1:4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - ereader-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ereader-net:
    driver: bridge
